apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s/demo:v1.0.0
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        failureThreshold: 3
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      hostPath:
        path: /var/lib/app
