apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s/demo:v1.0.0
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        periodSeconds: 2
        initialDelaySeconds: 2
        successThreshold: 1
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /
          port: 8000
